[2023-07-14T16:03:07.447480+00:00 INFO] [plan:263] ################################################################################
[2023-07-14T16:03:07.451167+00:00 INFO] [plan:264] Starting Reliably experiment: https://app.reliably.com/api/v1/organization/8b5fddfd-1da8-4586-934b-f184f0ef7904/experiments/bd7119c8-6ffb-4be7-9882-74f57292de78/raw
[2023-07-14T16:03:07.837408+00:00 DEBUG] [caching:24] Building activity cache...
[2023-07-14T16:03:07.837577+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-07-14T16:03:07.837724+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-07-14T16:03:07.837792+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-07-14T16:03:07.837878+00:00 DEBUG] [secret:78] Loading secrets...
[2023-07-14T16:03:07.837936+00:00 DEBUG] [secret:103] Done loading secrets
[2023-07-14T16:03:08.037868+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-07-14T16:03:08.038001+00:00 INFO] [experiment:109] Experiment looks valid
[2023-07-14T16:03:08.038055+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-07-14T16:03:08.038137+00:00 DEBUG] [caching:24] Building activity cache...
[2023-07-14T16:03:08.038186+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-07-14T16:03:08.038308+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-07-14T16:03:08.038394+00:00 DEBUG] [secret:78] Loading secrets...
[2023-07-14T16:03:08.038439+00:00 DEBUG] [secret:103] Done loading secrets
[2023-07-14T16:03:08.038484+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-07-14T16:03:08.038614+00:00 INFO] [run:369] Running experiment: Performs a range of checks on the certificate of a remote endpoint
[2023-07-14T16:03:08.041059+00:00 DEBUG] [__init__:64] Initializing controls
[2023-07-14T16:03:08.041238+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-07-14T16:03:08.041356+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-07-14T16:03:08.041574+00:00 DEBUG] [experiment:423] Configure Reliably's experiment control
[2023-07-14T16:03:08.041940+00:00 DEBUG] [experiment:587] Sending plan '5f12a148-ee40-4e35-b826-baf5aae4ead7' status: running
[2023-07-14T16:03:08.845762+00:00 INFO] [experiment:202] Reliably execution: 49977497-296d-471f-ab4b-cc7096424fdf
[2023-07-14T16:03:09.263290+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'running', 'started_on': '2023-07-14T16:03:08.041665+00:00', 'plan_id': '5f12a148-ee40-4e35-b826-baf5aae4ead7'}
[2023-07-14T16:03:09.594110+00:00 DEBUG] [experiment:81] Starting Reliably state checker now
[2023-07-14T16:03:09.594249+00:00 INFO] [run:396] Steady-state strategy: default
[2023-07-14T16:03:09.595631+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-07-14T16:03:09.595874+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'experiment'
[2023-07-14T16:03:09.596093+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-07-14T16:03:09.596390+00:00 DEBUG] [run:558] Running steady-state hypothesis before the method
[2023-07-14T16:03:09.596603+00:00 INFO] [hypothesis:186] Steady state hypothesis: Verify the conditions of your system
[2023-07-14T16:03:09.596823+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-07-14T16:03:09.597022+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-07-14T16:03:09.597233+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-07-14T16:03:09.597406+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-07-14T16:03:09.597616+00:00 INFO] [activity:215] Probe: verify-certificate
[2023-07-14T16:03:10.097593+00:00 DEBUG] [python:33] Activity 'verify-certificate' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-07-14T16:03:10.179468+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-07-14T16:03:10.179959+00:00 DEBUG] [activity:235]   => succeeded with 'True'
[2023-07-14T16:03:10.549050+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-07-14T16:03:10.549268+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-07-14T16:03:10.549355+00:00 DEBUG] [hypothesis:226] allowed tolerance is True
[2023-07-14T16:03:10.549434+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-07-14T16:03:10.549513+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-07-14T16:03:10.549576+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-07-14T16:03:10.549644+00:00 INFO] [run:679] Playing your experiment's method now...
[2023-07-14T16:03:10.549733+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'method'
[2023-07-14T16:03:10.549799+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-07-14T16:03:10.549854+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-07-14T16:03:10.549925+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'method'
[2023-07-14T16:03:10.549984+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-07-14T16:03:10.550050+00:00 DEBUG] [run:598] Running steady-state hypothesis after the method
[2023-07-14T16:03:10.550110+00:00 INFO] [hypothesis:186] Steady state hypothesis: Verify the conditions of your system
[2023-07-14T16:03:10.550182+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-07-14T16:03:10.550243+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-07-14T16:03:10.550324+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-07-14T16:03:10.550389+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-07-14T16:03:10.550452+00:00 INFO] [activity:215] Probe: verify-certificate
[2023-07-14T16:03:10.858148+00:00 DEBUG] [python:33] Activity 'verify-certificate' loaded from '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-07-14T16:03:10.924248+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-07-14T16:03:10.924487+00:00 DEBUG] [activity:235]   => succeeded with 'True'
[2023-07-14T16:03:11.235926+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-07-14T16:03:11.236216+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-07-14T16:03:11.236355+00:00 DEBUG] [hypothesis:226] allowed tolerance is True
[2023-07-14T16:03:11.236471+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-07-14T16:03:11.236625+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-07-14T16:03:11.236747+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-07-14T16:03:11.236884+00:00 WARNING] [run:722] Rollbacks were explicitly requested to be played
[2023-07-14T16:03:11.236987+00:00 INFO] [run:959] Let's rollback...
[2023-07-14T16:03:11.237143+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'rollback'
[2023-07-14T16:03:11.237251+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-07-14T16:03:11.237347+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-07-14T16:03:11.237480+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'rollback'
[2023-07-14T16:03:11.237590+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-07-14T16:03:11.237715+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-07-14T16:03:11.237826+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'experiment'
[2023-07-14T16:03:11.237927+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-07-14T16:03:11.238025+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-07-14T16:03:11.238128+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-07-14T16:03:11.238230+00:00 DEBUG] [python:192] Control module '/home/runner/work/resilience/resilience/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-07-14T16:03:11.238330+00:00 INFO] [experiment:248] Finishing Reliably execution...
[2023-07-14T16:03:11.638295+00:00 DEBUG] [experiment:163] Stopping Reliably state checker now
[2023-07-14T16:03:11.638714+00:00 DEBUG] [experiment:494] Completing execution '49977497-296d-471f-ab4b-cc7096424fdf' status: completed
[2023-07-14T16:03:11.974671+00:00 DEBUG] [experiment:587] Sending plan '5f12a148-ee40-4e35-b826-baf5aae4ead7' status: completed
[2023-07-14T16:03:12.266266+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'finished', 'status': 'completed', 'deviated': False, 'plan_id': '5f12a148-ee40-4e35-b826-baf5aae4ead7'}
[2023-07-14T16:03:12.775729+00:00 INFO] [experiment:311] Finished Reliably execution. Bye!
[2023-07-14T16:03:12.775970+00:00 DEBUG] [caching:42] Clearing activities cache
